# Generated by Django 2.0.8 on 2018-08-15 08:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pentadbiran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tatatertib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icno', models.CharField(max_length=14, unique=True, verbose_name='IC')),
                ('catatan', models.CharField(max_length=255, verbose_name='Catatan')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('createdby', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
