# Generated by Django 2.0.7 on 2018-08-21 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pentadbiran', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tatatertib',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NoKP', models.CharField(max_length=12, unique=True, verbose_name='No KP')),
                ('Catatan', models.CharField(max_length=255, verbose_name='Catatan')),
                ('Status', models.CharField(max_length=60, verbose_name='Status')),
                ('TkhDaftar', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('UserDaftar', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
